inherit_from: configs/Tum/tum.yaml
mapping:
  bound: [ [ -4.1 , 2.3 ],[ -5.6 , 3.0 ],[ -1.3 , 3.7 ]]
  marching_cubes_bound: [ [ -4.1 , 2.3 ],[ -5.6 , 3.0 ],[ -1.3 , 3.7 ]]
data:
  datadir: ./data/TUM/rgbd_dataset_freiburg1_rpy
  trainskip: 1
  output: output/TUM/fr1_rpy
  exp_name: demo_base

cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 8
  crop_size: [384,512]
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]

flow:
  flow_model: 'gma'  # gma, raft
  checkpoint: "checkpoints/gma-sintel.pth"  # raft-things.pth
  window_size: 4