inherit_from: configs/Tum/tum.yaml
mapping:
  bound: [[-6.,6],[-5,6],[-1.,3.]]
  marching_cubes_bound: [[-3.5,2.2],[-2.5, 2.5],[-0.1,3.]]

data:
  datadir: ./data/TUM/rgbd_dataset_freiburg3_sitting_halfsphere
  trainskip: 1
  output: output/TUM/fr3_sit_half
  exp_name: demo_base

cam:  #intrinsic is different per scene in TUM, this cam does not have distortion
  H: 480 
  W: 640
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6
  crop_edge: 8
  crop_size: [384,512]
  near: 0
  far: 5  # 5

flow:
  flow_model: 'gma'  # gma, raft
  checkpoint: "checkpoints/gma-sintel.pth"  # raft-things.pth
  window_size: 4