inherit_from: configs/BONN/bonn.yaml
mapping:
  bound: [ [ -2.9, 2.7 ],[ -0.2, 2.5 ],[ -5.2, 5.2 ] ]
  marching_cubes_bound: [ [ -2.9, 2.7 ],[ -0.2, 2.5 ],[ -5.2, 5.2 ] ]

data:
  datadir: ./data/BONN/rgbd_bonn_person_tracking2
  trainskip: 1
  output: output/BONN/bonn_person_track2
  exp_name: demo_base

cam:  #intrinsic is same per scene in BONN
  H: 480 
  W: 640
  fx: 542.822841
  fy: 542.576870
  cx: 315.593520
  cy: 237.756098
  crop_edge: 8
  crop_size: [450,600]
  distortion: [0.039903, -0.099343, -0.000730, -0.000144, 0.000000]
  near: 0.1
  far: 5